server:
  port: 8080

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopservices_product
  zipkin:
    base-url:http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
